# Generated by Django 3.2 on 2021-05-30 18:44

from django.db import migrations, models
import django.db.models.deletion
import documents.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapers', '0011_alter_retsinfosentences_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', documents.fields.EmbeddingField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='scrapers.retsinfodocument')),
            ],
        ),
    ]
