# Generated by Django 3.2 on 2021-05-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0011_alter_retsinfosentences_document'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentEmbeddings',
            new_name='DocumentEmbedding',
        ),
    ]
