# Generated by Django 3.2 on 2021-06-21 19:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import documents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0011_alter_retsinfosentences_document'),
        ('documents', '0002_rename_documentembeddings_documentembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_embedding', to='scrapers.retsinfodocument'),
        ),
        migrations.CreateModel(
            name='SentenceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', documents.fields.EmbeddingField()),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_embeddings', to='scrapers.retsinfodocument')),
            ],
        ),
    ]
