# Generated by Django 3.2 on 2021-06-22 16:40

from django.db import migrations
import documents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20210621_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=documents.fields.EmbeddingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceembedding',
            name='embedding',
            field=documents.fields.EmbeddingField(blank=True, null=True),
        ),
    ]
