# Generated by Django 3.2 on 2021-05-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetsinfoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField()),
                ('title', models.TextField()),
                ('short_name', models.CharField(max_length=500)),
                ('document_text', models.TextField()),
                ('is_historical', models.BooleanField()),
                ('ressort', models.CharField(max_length=255)),
                ('is_reprint', models.CharField(max_length=255)),
                ('geographic_id', models.IntegerField()),
                ('retsinfo_klassifikation_id', models.IntegerField()),
                ('has_fob_tags', models.BooleanField()),
                ('metadata', models.JSONField()),
                ('editorial_notes', models.JSONField()),
                ('alternative_media', models.JSONField()),
            ],
        ),
    ]
