# Generated by Django 3.2 on 2021-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_retsinfodocument_document_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retsinfodocument',
            name='is_reprint',
            field=models.BooleanField(),
        ),
    ]
