# Generated by Django 3.2 on 2021-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_alter_retsinfodocument_is_reprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetsinfoRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('headers', models.JSONField()),
                ('meta', models.JSONField()),
                ('priority', models.IntegerField()),
                ('encoding', models.CharField(max_length=25)),
                ('status', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=10)),
            ],
        ),
    ]
