# Generated by Django 3.2 on 2021-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_retsinforequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='retsinforequestlog',
            name='log_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
