# Generated by Django 3.2 on 2021-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_retsinforequestlog_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='retsinfodocument',
            name='document_nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retsinfodocument',
            name='document_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retsinforequestlog',
            name='document_nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retsinforequestlog',
            name='document_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
