# Generated by Django 3.2 on 2021-05-13 18:30

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0007_retsinfodocument_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='retsinfodocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='scrapers_re_search__7f46e2_gin'),
        ),
    ]
