# Generated by Django 3.2 on 2021-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0008_retsinfodocument_scrapers_re_search__7f46e2_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='retsinfodocument',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='retsinfodocument',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
