# Generated by Django 3.2 on 2021-05-30 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0009_auto_20210513_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetsinfoSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.retsinfodocument')),
            ],
        ),
        migrations.DeleteModel(
            name='RetsinfoRequestLog',
        ),
    ]
