# Generated by Django 3.2 on 2021-05-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0010_auto_20210530_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retsinfosentences',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='scrapers.retsinfodocument'),
        ),
    ]
