# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}

        script:
          cd /home/django/retsinformation
          su django
          source .env/bin/activate
          git pull origin master
          pip install -r requirements.txt
          cd retsinfo_app
          python manage.py collectstatic
          python manage.py makemigrations
          python manage.py migrate
          systemctl restart gunicorn