# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull & Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}

        script: |
          cd /home/django/retsinformation/retsinfo_app
          sudo -u django git pull
          sudo -u django .env/bin/pip install -r requirements.txt
          sudo -u django .env/bin/python manage.py collectstatic --noinput
          sudo -u django .env/bin/python manage.py makemigrations
          sudo -u django .env/bin/python manage.py migrate
          systemctl restart gunicorn